# 🔑 Alpaca API Keys (Keep this file private!)
ALPACA_API_KEY = "PK6TUU8PQAY50QN5MSF5"
ALPACA_SECRET_KEY = "CEmeaYj0k25JHtqGwodggjb9HEvx5tr371XEnVBJ"
BASE_URL = "https://paper-api.alpaca.markets"  # Paper Trading Mode

# 📊 NIFTY 50 Stocks for Assignment
NIFTY_50_STOCKS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "KOTAKBANK.NS",
    "AXISBANK.NS", "ASIANPAINT.NS", "MARUTI.NS", "HCLTECH.NS", "SUNPHARMA.NS",
    "ULTRACEMCO.NS", "TITAN.NS", "BAJFINANCE.NS", "WIPRO.NS", "NESTLEIND.NS",
    "POWERGRID.NS", "TECHM.NS", "BAJAJFINSV.NS", "NTPC.NS", "ONGC.NS",
    "ADANIENT.NS", "JSWSTEEL.NS", "COALINDIA.NS", "TATAMOTORS.NS", "INDUSINDBK.NS",
    "CIPLA.NS", "DRREDDY.NS", "SHREECEM.NS", "BRITANNIA.NS", "EICHERMOT.NS",
    "HEROMOTOCO.NS", "DIVISLAB.NS", "GRASIM.NS", "ADANIPORTS.NS", "TATACONSUM.NS",
    "BPCL.NS", "UPL.NS", "HINDALCO.NS", "VEDL.NS", "SBILIFE.NS", "TATASTEEL.NS",
    "HDFC.NS", "APOLLOHOSP.NS", "ICICIGI.NS", "SBI.NS", "BAJAJ-AUTO.NS"
]

# 📈 Assignment Strategy Parameters
RSI_BUY_THRESHOLD = 30
RSI_SELL_THRESHOLD = 70
SMA_SHORT = 20
SMA_LONG = 50

# 📊 Google Sheets Configuration
GOOGLE_SHEETS_CREDENTIALS_FILE = "credentials.json"  # Download from Google Cloud Console
SPREADSHEET_ID = "YOUR_SPREADSHEET_ID"  # Create a Google Sheet and get its ID

# 📱 Telegram Configuration
TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ID = "YOUR_TELEGRAM_CHAT_ID"
